apiVersion: apps/v1
kind: Deployment
metadata:
  name: digital-card
  namespace: 2401002
spec:
  replicas: 1
  selector:
    matchLabels:
      app: digital-card
  template:
    metadata:
      labels:
        app: digital-card
    spec:
      imagePullSecrets:
        - name: nexus-secret
      containers:
        - name: digital-card
          image: nexus-service-for-docker-hosted-registry.nexus.svc.cluster.local:8085/project-namespace/digital-card:latest
          ports:
            - containerPort: 80
