apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: digital-card-ingress
  namespace: roll_2401002
spec:
  rules:
  - host: digital-card-roll2401002.imcc.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: digital-card-service
            port:
              number: 80
              
