apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: digital-card-ingress
  namespace: 2401002
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: 2401002.imcc.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: digital-card-service
                port:
                  number: 80
