apiVersion: v1
kind: Service
metadata:
  name: digital-card-service
  namespace: roll_2401002
spec:
  selector:
    app: digital-card
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
